### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zghwi** [programmeruser2/os#3]
how in the blue hell did you made an OS Canvas
with WASM?

**Comment by programmeruser2** [comment]
What are you exactly talking about here?

**Comment by zghwi** [comment]
oh im sorry
your https://programmeruser.repl.co
you booted up a kernel in a canvas

**Comment by programmeruser2** [comment]
That website is unrelated to this repo. It's the Linux kernel with Busybox and a shell script, booted with GRUB in v86.

**Comment by zghwi** [comment]
oh ok
that's awesome!!
